### ISSUE TITLE
Why not disposing the MsieJsEngine?

### ISSUE THREAD

**Issue by danielwertheim** [SimonCropp/Chevron#10]
Why is not the internal `MsieJsEngine` disposed? https://github.com/SimonCropp/Chevron/blob/master/Chevron.IE/Handlebars.cs#L203

https://github.com/Taritsyn/MsieJavaScriptEngine/blob/master/MsieJavaScriptEngine/MsieJsEngine.cs#L600

**Comment by SimonCropp** [comment]
It is disposed https://github.com/Fody/Janitor

**Comment by danielwertheim** [comment]
Nice. Didn't know about that one.
