### ISSUE TITLE
RegisterTemplate fails if name contains integers

### ISSUE THREAD

**Issue by danielwertheim** [SimonCropp/Chevron#11]
Got the exception when I generated some "names" using `Guid.NewGuid().ToString("n")`. So essentially;

```csharp
var handlebars = new Chevron.Handlebars();
handlebars.RegisterTemplate(Guid.NewGuid().ToString("n"), content);
```

Tried passing `"1"`, fails as well.

`MsieJavaScriptEngine.JsRuntimeException : Compile error: Expected identifier`

**Comment by SimonCropp** [comment]
it is because the templates are registered as JS methods which cant start with a number. I will throw a more useful exception
