### ISSUE TITLE
[Q] What is Approvals?

### ISSUE THREAD

**Issue by dehghani-mehdi** [SimonCropp/Chevron#15]
Hi,

I tired `Chevron.IE`, `Chevron.IE.Merged` and `Chevron.Jint` but no success.
Also Added `MsieJavaScriptEngine`.

Which assembly is for `Approvals`?

Thanks.

**Comment by SimonCropp** [comment]
sorry what r u trying to do? build the solution? use the nuget?

**Comment by dehghani-mehdi** [comment]
I'm trying to run your first example:

```
var source = @"<p>Hello, my name is {{name}}. I am from {{hometown}}. I have ' +
        '{{kids.length}} kids:</p>' +
        '<ul>{{#kids}}<li>{{name}} is {{age}}</li>{{/kids}}</ul>";

var context = new
{
    name = "Alan",
    hometown = "Somewhere, TX",
    kids = new[]
        {
            new
            {
                name = "Sally",
                age = "4"
            }
        }
};

using (var handleBars = new Handlebars())
{
    handleBars.RegisterTemplate("myTemplate", source);
    Approvals.Verify(handleBars.Transform("myTemplate", context));
}
```

**Comment by SimonCropp** [comment]
That is because I copied it from a test. It just asserts the result from the method call

**Comment by dehghani-mehdi** [comment]
So, using 

    handleBars.Transform("myTemplate", context)

Instead of

    Approvals.Verify(handleBars.Transform("myTemplate", context));

Is the right way to work with `Chevron`?

**Comment by SimonCropp** [comment]
Yes

**Comment by dehghani-mehdi** [comment]
Thanks for the support and `Chevron`.

Maybe you should update the `README` and remove/add comment about `Approvals`.

**Comment by SimonCropp** [comment]
done
