### ISSUE TITLE
Run additional scripts after loading handlebars

### ISSUE THREAD

**Issue by yannisgu** [SimonCropp/Chevron#6]
A lot of handlebars helpers are distributed as collection of helpers in one .js file.
Now in Chevron it is necessary to register each helper separtly. 
It would be handier if somewhere a set of files to run after running handlebars.js could be specified to register those helpers.

**Comment by SimonCropp** [comment]
there is a constructor that takes in a JS engine. so you can add any scripts you want before a render
https://github.com/SimonCropp/Chevron/blob/master/Chevron.IE/Handlebars.cs#L16

Also all member are virtual so you should be able to change the behaviour of any of them. 

So i am not sure what you "cant do". 

Perhaps you could show me in a pull request?

**Comment by yannisgu** [comment]
What I would like to achive is to run scripts **after** handlebars is loaded, but before  anything is rendered. 

To enable this Handlerbars.cs needs a public property `Engine` or a method `ExecuteScript(string script)`

**Comment by SimonCropp** [comment]
The handlebars is loaded in the constructor.  So why cant you do this 

    var msieJsEngine = new MsieJsEngine(JsEngineMode.Auto);
        using (var handleBars = new Handlebars(msieJsEngine))
        {
            msieJsEngine.Execute("my Js to run before rendering");
            handleBars.RegisterTemplate("Index", source);
            Approvals.Verify(handleBars.Transform("Index", null));
        }

**Comment by yannisgu** [comment]
Ohh, yeah, of course!
