### ISSUE TITLE
Non-Windows platforms

### ISSUE THREAD

**Issue by Daniel15** [SimonCropp/Chevron#7]
From the readme:

> V8 will, in theory, run on a non windows platform (I have not done any testing of this).

Unfortunately this isn't the case with ClearScript. ClearScript only works on Windows as it uses C++/CLI which is not cross-platform. There are ways to use V8 from Linux or Mac OS, but you need to use a different JavaScript engine. In ReactJS.NET I'm using [a fork of VroomJs](https://github.com/Daniel15/vroomjs) with JavaScriptEngineSwitcher. VroomJs does run from Mono as it's got a vanilla C interface.

**Comment by SimonCropp** [comment]
so r u proposing instead taking a dependency on JavaScriptEngineSwitcher?

**Comment by Daniel15** [comment]
Up to you :) I've found it to be a pretty good abstraction layer for supporting different engines. However, JavaScriptEngineSwitcher doesn't come with an adapter for VroomJs so I'm just using my own one: https://github.com/reactjs/React.NET/blob/master/src/React.JavaScriptEngine.VroomJs/VroomJsEngine.cs

Since you support Jint, perhaps V8 support on Linux or Mac isn't really necessary (as Jint can just be used on those platforms)

**Comment by SimonCropp** [comment]
happy to accept a PR for JavaScriptEngineSwitcher. I dont have a need for it ATM so prob wont get around to it any time soon

**Comment by SimonCropp** [comment]
closing this as I dont currently need it. feel free to send a PR if you do
