### ISSUE TITLE
Q: life cycle of Handlebars and concurrency

### ISSUE THREAD

**Issue by danielwertheim** [SimonCropp/Chevron#9]
What is the recommendation of "life cycle" of e.g. https://github.com/SimonCropp/Chevron/blob/master/Chevron.IE/Handlebars.cs

And what about concurrent use of it, since you seem to only check against existence of e.g. templates in ordinare `List<string>`? Hence multiple same calls to `engine.Execute` can happen?

Are we supposed to use one instance per call or to handle concurrency in calling code?

**Comment by SimonCropp** [comment]
well there is one instance of a JS engine per Handlebars instance so this is really a question for the individual engine you choose.

**Comment by SimonCropp** [comment]
for example https://github.com/Taritsyn/MsieJavaScriptEngine/issues/3
